app:
  dbone:
    datasource:
      class-driver: com.mysql.jdbc.Driver
      username: root
      password: dasha09092003
      url: jdbc:mysql://localhost:3306/intership
  dbtwo:
    datasource:
      class-driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: root
      url: jdbc:sqlserver://localhost:1433;databaseName=sql_ms;encrypt=true;trustServerCertificate=true;
